models_data = {
    'Москва': [
        {'name': 'Катя', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСтильная и уверенная в себе модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Ксения', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая и жизнерадостная личность.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Даша', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭнергия и позитив в каждой фотографии.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Карина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с уникальным стилем.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Ария', 'age': 18, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМолодая и амбициозная модель.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Кристина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОчаровательная и романтичная натура.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'},
        {'name': 'Алиса', 'age': 19, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТворческая и креативная личность.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Дарья', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбладает невероятным шармом.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Ангелина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСияющая и яркая личность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Алина', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантная и утонченная модель.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Лика', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и интересная личность.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'}
    ],
    'Ижевск': [
        {'name': 'Анна', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСтрогая и профессиональная модель.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Мария', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЛегкость и обаяние в каждой фотосессии.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Александра', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭнергия и позитив в каждом кадре.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
    ],
    'Санкт-Петербург': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Казань': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Нижний Новгород': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Ростов-на-Дону': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Уфа': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Челябинск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Краснодар': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Самара': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Владивосток': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Екатеринбург': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Новосибирск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Воронеж': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Омск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Красноярск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Пермь': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Волгоград': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Тюмень': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Барнаул': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Благовещенск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Ставрополь': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Архангельск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Калуга': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Чебоксары': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Тула': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Ярославль': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Саранск': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Набережные Челны': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Кемерово': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ],
    'Сочи': [
        {'name': 'Арина', 'age': 24, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nНеповторимый стиль и шарм.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Алина', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМечтательница с яркими амбициями.', 'photo': './models_photo/msk-model-1_2.jpg', 'photo2': './models_photo/msk-model-1_3.jpg'},
        {'name': 'Полина', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЧувствительная и творческая личность.', 'photo': './models_photo/model-3.jpg', 'photo2': './models_photo/model-3-2.jpg'},
        {'name': 'Юлия', 'age': 23, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nУмение привлекать внимание.', 'photo': './models_photo/model-8.jpg', 'photo2': './models_photo/model-8-2.jpg'},
        {'name': 'Анастасия', 'age': 20, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nТалантливая и привлекательная модель.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Маргарита', 'age': 27, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nСмелая и решительная.', 'photo': './models_photo/model-5.jpg', 'photo2': './models_photo/model-5-2.jpg'},
        {'name': 'Лариса', 'age': 26, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЭлегантность и стиль.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Вероника', 'age': 25, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЖивой ум и прекрасное чувство стиля.', 'photo': './models_photo/model-2.jpg', 'photo2': './models_photo/model-2-2.jpg'},
        {'name': 'Евгения', 'age': 29, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМодель с большим опытом.', 'photo': './models_photo/model-4.jpg', 'photo2': './models_photo/model-4-2.jpg'},
        {'name': 'Катя', 'age': 28, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЗагадочная и притягательная.', 'photo': './models_photo/msk-model-1.jpg', 'photo2': './models_photo/msk-model-1_4.jpg'},
        {'name': 'Нина', 'age': 30, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nМудрость и опыт в каждом кадре.', 'photo': './models_photo/model-7.jpg', 'photo2': './models_photo/model-7-2.jpg'},
        {'name': 'Диана', 'age': 22, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nЯркая индивидуальность.', 'photo': './models_photo/model-9.jpg', 'photo2': './models_photo/model-9-2.jpg'},
        {'name': 'Снежана', 'age': 21, 'description': 'Час - 4100₽\n2 часа - 7925₽\nНочь - 16400₽\nОбаяние и грация.', 'photo': './models_photo/model-6.jpg', 'photo2': './models_photo/model-6-2.jpg'}
    ]
}